### ISSUE TITLE
exponent != 0, {'value': 1000, 'exponent': 64050}

### ISSUE THREAD

**Issue by siyangyuandegit** [atomicals/atomicals-electrumx#101]
when i pull the lastest code, the node can't work ?
  File "/mnt/btc_node_disk/atomicals-electrumx/electrumx/lib/atomicals_blueprint_builder.py", line 252, in build_nft_input_idx_to_atomical_map
    assert(exponent == 0)
AssertionError
the exponent is 
-----
{'value': 1000, 'exponent': 64050}
what happend?

**Comment by siyangyuandegit** [comment]
{'atomical_id': b'\x85\xfd\xda\xd7\x14\x98\xb4\xb7:\xbb\xf2\xde\xf0\xc8/\xdcI\x83\x18\x1f\x8c\xb5\x85DK\xad#\xfa\x96\xe5\xbb\xbf\x00\x00\x00\x00', 'location_id': b',\x05Z&\x03daVM\xa1\xfby\xa9\n\xa6\xee\x7f5\x14\xbc\xc5\xa1\x97\xae"\xc7!!\xfe\x13\x1d\x83\x00\x00\x00\x00', 'data': b'v\xd7_n\xf8\xe8n\xd2\xee2\xd8\r\xbe C\x94\x83z@/\x06\x8a}i\xc7\x08\xbc\x0f\xd0.\xa9LO\xa2\xa3\x99{\x03uf\t\xa8X\xe8\x03\x00\x00\x00\x00\x00\x002\xfa96\x00', 'data_ex': {'value': 1000, 'exponent': 64050}}
more info

**Comment by dubuqingfeng** [comment]
Exponent is always 0 for NFTs.
So what is this transaction?

**Comment by siyangyuandegit** [comment]
I don't konw ... my node has not worked?

**Comment by shadowv0vshadow** [comment]
```
def get_nominal_token_value(value, exponent):
    assert(value >= 0)
    assert(exponent >= 0)
    return value
    return value / (10**exponent)

def get_adjusted_sats_needed_by_exponent(value, exponent):
    return value
    return int(value * (10**exponent))
```

```
        exponent = atomicals_entry['data_ex']['exponent']
        if exponent != 0:
           exponent = 0
```

Waring!!! This code just use for debug.
You need to synchronize all nodes from the beginning.

**Comment by renmengkai** [comment]
![1706772422295](https://github.com/atomicals/atomicals-electrumx/assets/31378513/662ce1a2-3698-428d-a580-8ae076d64692)
I have encountered the same problem, how can I solve it?

**Comment by shadowv0vshadow** [comment]
> ![1706772422295](https://private-user-images.githubusercontent.com/31378513/301420451-662ce1a2-3698-428d-a580-8ae076d64692.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODQ0ODcsIm5iZiI6MTcwNjc4NDE4NywicGF0aCI6Ii8zMTM3ODUxMy8zMDE0MjA0NTEtNjYyY2UxYTItMzY5OC00MjhkLWE1ODAtOGFlMDc2ZDY0NjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDEwNDMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlNGY0YTJkNDRhYWQwMDczNWNiMTVkMGMzOTA0MDUzMDYwNGYwYTNjM2E1NDBkMDRkMTE2YTI5YWI2ZDZhNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vpL-a8ycxKN_8BOZq9dyLcceHIu9Awv1eM8OpeIwhbQ) I have encountered the same problem, how can I solve it?

Reindex from the beginning.
