### ISSUE TITLE
The command server-version doesn't work.

### ISSUE THREAD

**Issue by FrozenRaspberry** [atomicals/atomicals-electrumx#11]
It seems that in the js CLI help there's a command for checking server version.

But it returns 500 when execute.

Is it possible to support the version command so we can check the version num of server?

**Comment by YuXiaoCoder** [comment]
Official nodes can't get version information either
```bash
curl -s -X GET https://ep.atomicals.xyz/proxy/server.version | jq
{
  "success": false,
  "code": 1,
  "message": "server.version already sent"
}
```

**Comment by FrozenRaspberry** [comment]
> Are you current on the data sync?

No, the node is up to date. Just the "server-version" cmd doesn't work. Other commands work fine (get-ticker, balance... etc)

**Comment by yvvw** [comment]
```diff
diff --git electrumx/server/session.py electrumx/server/session.py
index 945d480..c03018f 100644
--- electrumx/server/session.py
+++ electrumx/server/session.py
@@ -1028,7 +1028,6 @@ class ElectrumX(SessionBase):
         self.subscribe_headers = False
         self.connection.max_response_size = self.env.max_send
         self.hashX_subs = {}
-        self.sv_seen = False
         self.mempool_statuses = {}
         self.set_request_handlers(self.PROTOCOL_MIN)
         self.is_peer = False
@@ -2374,9 +2373,6 @@ class ElectrumX(SessionBase):
         protocol_version: the protocol version spoken by the client
         '''
         self.bump_cost(0.5)
-        if self.sv_seen:
-            raise RPCError(BAD_REQUEST, f'server.version already sent')
-        self.sv_seen = True

         if client_name:
             client_name = str(client_name)
```

```sh
# fixed by patch. but api response incorrect information
patch -p0 < server_version_api.patch
```

**Comment by AlexV525** [comment]
`server.features` should be used in this case instead. We'd probably considering bring this feature accurate about Atomicals, and also combining AIPs.

**Comment by chagelstein** [comment]
> It seems that in the js CLI help there's a command for checking server version.
> 
> But it returns 500 when execute.
> 
> Is it possible to support the version command so we can check the version num of server?

Use ELECTRUMX_PROXY_BASE_URL=https://ep.atomicals.org/proxy in your .env file
