### ISSUE TITLE
Add flag for find_container, find_ticker, find_realm, etc for `is_verified_only=True` to only return verified candidates in result set.

### ISSUE THREAD

**Issue by atomicals** [atomicals/atomicals-electrumx#126]
For example: https://ep.atomicals.xyz/proxy/blockchain.atomicals.find_containers?params=%5B%22%22%2C1%5D&_=1670&pretty

Currently returns ALL verified and other candidate status. What is needed is an option to return the verified ones only and also indicate in the results.

**Comment by atomicals** [comment]
Also add for dmitems to be able to be queried same way

**Comment by AlexV525** [comment]
The default should be `False` to avoid breaking previous calls.
