### ISSUE TITLE
When a block index is completed, push an index completion event to the proxy

### ISSUE THREAD

**Issue by iota9star** [atomicals/atomicals-electrumx#153]
The data in the index is updated only after indexing a block, and before indexing a new block, all data remains unchanged. Implementing a caching layer in the proxy can significantly reduce requests reaching the indexer, thereby enhancing system performance.

If a completion event is sent to the proxy after indexing is complete, the proxy can clear the cache upon receiving the event. This enables real-time updates to the data.

**Comment by AlexV525** [comment]
You can subscribe to the block notification by requesting `blockchain.headers.subscribe`. The session manager will notify every session with the message that the block has been indexed.

```json
{
  "jsonrpc": "2.0",
  "method": "blockchain.headers.subscribe",
  "params": [
    {
      "hex": "00400020fae1aceb1dbb35b1ac1fa03986e1c85d0d742fe2b77878941500000000000000f2948fb0d72d63454a5ad073609a4cec0e384f7de729a4db2358dd4bde488df773ba0366434e2c19807dad2a",
      "height":2583779
    }
  ]
}
```
