### ISSUE TITLE
api unavailable

### ISSUE THREAD

**Issue by blocknodehub** [atomicals/atomicals-electrumx#20]
I started the node, but how do I use the api calls
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:60022           0.0.0.0:*               LISTEN  

curl http://127.0.0.1:8000/health | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (1) Received HTTP/0.9 when not allowed

**Comment by AlexV525** [comment]
1. Use a proxy to handle calls, e.g. https://github.com/WizzWallet/elex-proxy
2. Setup an HTTP service in the .env to make HTTP calls directly.
