### ISSUE TITLE
need snapshots

### ISSUE THREAD

**Issue by dubuqingfeng** [atomicals/atomicals-electrumx#31]
May I ask if there are height snapshots before 808080?
And the latest snapshot.

**Comment by AI-Chef** [comment]
your can download from magnet:?xt=urn:btih:7KW5OXSWUQ2EFF57URE42GBRL2XCN5AI&dn=ElectrumX-Data-20231114

**Comment by lucky2077** [comment]
> your can download from magnet:?xt=urn:btih:7KW5OXSWUQ2EFF57URE42GBRL2XCN5AI&dn=ElectrumX-Data-20231114

**Do not use this data**

The index files genrated with old version.

For v1.3.6, you should resync from the begining, there's no snapshot for block height 808080.
