### ISSUE TITLE
late to pull the latest code for bugfix 

### ISSUE THREAD

**Issue by hotbroker** [atomicals/atomicals-electrumx#43]
how to re-index from ATOMICALS_ACTIVATION_HEIGHT_COMMITZ = 822800
SHA-1: 88039346b815cd04bb9f5b07d9ed54734f11ec24

* Prevent decentralized mint from reusing bitwork for more than one output

**Comment by AlexV525** [comment]
Delete the DB folder and restart the indexer will trigger the reindex.
