### ISSUE TITLE
Resolve the issue of losing atomical assets when using other wallets

### ISSUE THREAD

**Issue by infra403** [atomicals/atomicals-electrumx#47]
https://twitter.com/atomicalsmarket/status/1719342168710529131

This one important !

Many user report that they have lost atomical assets  while using [#UNISAT](https://twitter.com/hashtag/UNISAT?src=hashtag_click) wallet. 

To be clear that, Unisat wallet is for ordinals not atomical. So please don't us it for holding atomical, Just use it for inscribing atomical.

**Comment by infra403** [comment]
Can BTC transfers be separated from ARC20 token transfers, so that when there is no change in ARC20 tokens, it's not necessary to add the corresponding stats?

**Comment by AlexV525** [comment]
Use wallets that support Atomicals or there is no way to avoid assets lost.

Additionally, the discussion can take place on Twitter, rather than this artifact repo.
