### ISSUE TITLE
Index data error

### ISSUE THREAD

**Issue by sankinyue** [atomicals/atomicals-electrumx#6]
Using Bitcoin Network, I found that this tx_id is also in line with atomicals protocol.

```
    "commitTxid": "01238593c66538df0188c546cad3ceecbef94d395c105f1e933fdb61cdcceec1"
    "revealTxid": "c2acaaa3cd87d1865ab10392cd41e615a5785a90ef0a692f3cf2d5b783ad25ce"
```

This tx_id is a realm, named `blocktime`.

But I don’t know why this tx_id is not indeed, and similar TX still has

808676 ticker: kekw
```
    "commitTxid": "6969a78a1656f86339aaae1ae71bc233bfc98bbea7ea7cea9c5f5793420aeaff"
    "revealTxid": "0x0d72b7b63889bd89cb9290060a4ea66c8edfd2b5beb406e759ab50c34f7a777e"
```

808684 ticker: rekt
```
    "commitTxid": "13373bdbcf78618fc949854b51101f60379cd2d318328709bbe266a505ced9c9"
    "revealTxid": "ce18bfa286d0f49997715b882f99df27cdc58e05d33e93d15c46164e988a798d"
```

I would like to know if there are any other rules or conditions to determine if the initialization of 
```
OP_PUSHBYTES_4 61746f6d
OP_PUSHBYTES_3 646d74 (6e6674)
```
is correct.

**Comment by atomicals** [comment]
The commit and reveal are more than 3 block confirmations apart. It is too late. The commit and reveal must be within 3 blocks for it to be a valid mint for a realm/dmitem/subrealm/container/ticker
