### ISSUE TITLE
v.1.3.8.0 api blockchain.atomicals.get_ft_info  is error 

### ISSUE THREAD

**Issue by imangoMah** [atomicals/atomicals-electrumx#95]
<img width="1099" alt="image" src="https://github.com/atomicals/atomicals-electrumx/assets/121002588/7ae0171d-6f7b-42a5-b7f1-0c6084f8bea3">

After updating the node version to v.1.3.8.0, I am unable to use blockchain. atomicals. get_ Ft_ Info API, node prompts error in the above image, KeyError: $mint_ Mode

**Comment by AlexV525** [comment]
https://ep.wizz.cash/proxy/blockchain.atomicals.get_ft_info?params=[%22777778541689ad09e43eeba8e9df62981c32d9fdc7fdbb7aff87cd3267bcd90di0%22]
